version: "3.3"

services:

  mysql:
      build:
        context: .
        dockerfile: Dockerfile-mysql
      environment:
        MYSQL_ROOT_PASSWORD: "test123"
        MYSQL_DATABASE: "mysql1"
      ports:
        - 3309:3306

  adminer:
      build:
        context: .
        dockerfile: Dockerfile-adminer
      ports:
        - 9000:8080